name: Static checks

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*.*'
  pull_request:
    branches:
      - main

env:
  ASDF_APP_DIR: ${{ github.workspace }}/.cache/asdf
  ASDF_DATA_DIR: ${{ github.workspace }}/.cache/asdf-data
  ASDF_DEFAULT_TOOL_VERSIONS_FILENAME: ${{ github.workspace }}/.tool-versions
  # renovate: datasource=github-releases depName=asdf-vm/asdf
  ASDF_VERSION: v0.14.1
  FORCE_COLOR: 1
  PIP_CACHE_DIR: .cache/pip
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_PROGRESS_BAR: "off"
  PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit
  PRE_COMMIT_COLOR: always
  # renovate: datasource=github-releases depName=pre-commit/pre-commit
  PRE_COMMIT_VERSION: 4.0.1
  PYTHONUNBUFFERED: 1
  # renovate: datasource=python-version depName=pre-commit-python packageName=python
  PYTHON_VERSION: 3.13.0
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.XDG_CACHE_HOME }}
          key: pre-commit-${{ env.PYTHON_VERSION }}-${{ env.PRE_COMMIT_VERSION }}-${{ env.ASDF_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles(env.ASDF_DEFAULT_TOOL_VERSIONS_FILENAME) }}

      - name: Asdf install
        run: |
          if [ -f .tool-versions ]; then
            mkdir -p "${ASDF_DATA_DIR}"
            chmod -R a+rwx "${ASDF_DATA_DIR}"
            if [[
              ! -d "${ASDF_APP_DIR}" ||
              ! -f "${ASDF_APP_DIR}/asdf.sh"
            ]]; then
              [ -e "${ASDF_APP_DIR}" ] && rm -rf "${ASDF_APP_DIR}"
              git clone https://github.com/asdf-vm/asdf.git "${ASDF_APP_DIR}" --branch "${ASDF_VERSION}" \
              -c advice.detachedHead=false --depth 1
              rm -rf "${ASDF_APP_DIR}/.git"
              chmod a+x "${ASDF_APP_DIR}/asdf.sh"
            fi
            source "${ASDF_APP_DIR}/asdf.sh"
            cut -d' ' -f1 .tool-versions | grep "^[^\#]" | xargs -I {} asdf plugin add {}
            asdf install
          fi
          mkdir -p "${ASDF_APP_DIR}"
          mkdir -p "${ASDF_DATA_DIR}"
          chmod -R a+rwx "${ASDF_DATA_DIR}"

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit==${{ env.PRE_COMMIT_VERSION }}

      - name: Run pre-commit
        run: |
          source "${ASDF_APP_DIR}/asdf.sh"
          if [[ -n "${{ github.base_ref }}" ]]; then
            PR_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            git fetch --quiet origin "${{ github.base_ref }}" "${PR_BRANCH}"
            pre-commit run --from-ref "origin/${{ github.base_ref }}" --to-ref "origin/${PR_BRANCH}" --show-diff-on-failure
          else
            pre-commit run --all-files --show-diff-on-failure
          fi
