name: Draft a Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3
        with:
          useConfigFile: true

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: ${{ github.ref_name }}
          draft: true
          generateReleaseNotes: true
          makeLatest: true
          name: ${{ steps.gitversion.outputs.semVer }}
          prerelease: false
          tag: ${{ steps.gitversion.outputs.semVer }}
          updateOnlyUnreleased: true
