name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v42.0.6
        env:
          LOG_LEVEL: info
        with:
          configurationFile: config.js
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|AWS_TOKEN|AZURE_ACCESS_TOKEN)$"
          token: ${{ secrets.RENOVATE_TOKEN }}
