name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v41.0.5
        env:
          RENOVATE_TOKEN: ${{ github.GITHUB_TOKEN }}
          GITHUB_COM_TOKEN: ${{ github.GITHUB_TOKEN }}
        with:
          token: ${{ github.GITHUB_TOKEN }}
